# Generated by Django 2.2.10 on 2021-10-07 17:24

from django.db import migrations, models
import django.db.models.deletion
import polls.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название опроса')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания опроса')),
                ('start_date', models.DateTimeField(validators=[polls.validators.date_validator], verbose_name='Дата начала опроса')),
                ('end_date', models.DateTimeField(validators=[polls.validators.date_validator], verbose_name='Дата окончания опроса')),
                ('description', models.TextField(help_text='Укажите тематику опроса.', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
