# Generated by Django 2.2.10 on 2021-10-07 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('Reply in text', 'Reply in text'), ('Pick one option', 'Pick one option'), ('Pick more than one option', 'Pick more than one option')], default=django.utils.timezone.now, max_length=50, verbose_name='Тип вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(help_text='Укажите тематику и цель опроса.', verbose_name='Описание'),
        ),
    ]
