# Generated by Django 2.2.10 on 2021-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211008_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(help_text='Укажите уникальный ID.', verbose_name='Пользователь'),
        ),
    ]
